### PR TITLE
Editing Data Warehouse Connecting Docs

### PR DESCRIPTION
**Pull request by hanson377**
Since we have made a massive upgrade to our warehouse connection flows, we need to update our docs.

### CODE REVIEW

**Review by carlineng — APPROVED** [review]
LGTM!

**Comment by carlineng** [comment]
My only suggestion would be to change `Service User` in the Snowflake section to `service User` (lowercase `s`). Having it capitalized might confuse some users that `Service User` is a specific concept within Snowflake, when it's actually just a `User` that is dedicated to our service.

**Comment by hanson377** [comment]
Makes sense to me, Carlin. I'll change that now.

**Comment by hanson377** [comment]
Does anyone have any idea as to if this just deploys automatically? Or is there something I need to do to deploy it myself?

**Comment by hanson377** [comment]
Oh! Nevermind. Looks like the results are live.

**Pull request merged**
