### PR TITLE
Added a relationship map

### PR DESCRIPTION
**Pull request by Summchestnuts**
@megan-eppo Please let me know if this looks alright. Not sure how to resize the image, if possible, we should have the map a bit small but it can be clicked to view the full image.

### CODE REVIEW

**Review by megan-eppo — COMMENTED** [review]
You can try seeing if wrapping the image in html works
`Eppo Product Relationship Map`

**Comment by Summchestnuts** [comment]
> You can try seeing if wrapping the image in html works `Eppo Product Relationship Map`

I tried, and it didn't work, but maybe I'm not getting this right... Let me ask about around and figure it out

**Comment by vpai** [comment]
@Summchestnuts this is a great diagram! But I feel like if I'm new to the Eppo and reading this I'm very confused by all the complexity. One small step here that might help a bit would be adding the numbers of the list below to the actual diagram, that way I can map the diagram to the text below easily. Otherwise I feel like we're leaving people hanging by introducing a really complex picture to an already complex page.

**Comment by Summchestnuts** [comment]
That is an awesome idea!!!!!!! I’ll edit the map and update this. Thank you!

**Comment by Summchestnuts** [comment]
@vpai what do you think about this?
Summer's random board - Relationship Map

**Comment by Summchestnuts** [comment]
@vpai do you want to change the map to the one above with numbers matching the overview?

**Pull request merged**
